### ISSUE TITLE
Seeding error on joins table

### ISSUE THREAD

**Issue by mngatewood** [mngatewood/gh-deckbuilder#4]
Rectified by manual rollback and migrate latest before seeding.

Error seeding card data: error: insert into "joins" ("card_id", "deck_id") values ($1, $2) - insert or update on table "joins" violates foreign key constraint "joins_card_id_foreign"

AND

Error seeding card data: error: delete from "cards" - update or delete on table "cards" violates foreign key constraint "joins_card_id_foreign" on table "joins"

**Comment by CharlesY712** [comment]
On this line in /db/seeds/test/cards.js (https://github.com/mngatewood/gh-deckbuilder/blob/ab7813542079a3e91e792153aa632fbd1184b7b2/db/seeds/test/cards.js#L3)

const environment needs to = process.env.NODE_ENV || 'test'

This will resolve the issue until server.js has set up the environment.
